function loadAppfile(){var a=document.getElementById("menu");if(null!=a)for(var a=a.getElementsByTagName("a"),b=a.length;0<b;)a[--b].title="";bw=$(document).width();if(typeof f!=='undefined'){if(w>bw){h=(bw/w)*h
w=bw}
var params={};params.allowfullscreen="true";params.hasPriority="true";if(typeof wm==='undefined'){params.wmode='"'+'window'+'"';params.bgColor=document.bgColor;}else{params.wmode='"'+ wm+'"';}
params.allowScriptAccess="always";if(swfobject.hasFlashPlayerVersion("6.0.0")){swfobject.embedSWF("/swf/"+ f+".swf","Online-Stopwatch",w,h,"6.0.0",false,flashvars,params);}}
JSopts=[];console.log("version 5.3")
if(typeof flashvars!=='undefined'){if(typeof flashvars.ns!=='undefined'){JSopts.push('ns='+ flashvars.ns);}
if(typeof flashvars.nslen!=='undefined'){JSopts.push('nslen='+ flashvars.nslen);}
if(typeof flashvars.sf!=='undefined'){JSopts.push('countdown='+ flashvars.sf);}
tmpOb='';if(JSopts.length>0){for(var i in JSopts){tmpOb=tmpOb+'&'+ JSopts[i];}
JSopts='?'+ tmpOb;}}
if(JSopts.length==0){JSopts='';}
if(typeof gsh5!=='undefined'){if(!swfobject.hasFlashPlayerVersion("6.0.0")){if(typeof hf!=='undefined'){document.getElementById("Online-Stopwatch").innerHTML='<iframe id="fullframe" src="http://www.online-stopwatch.com/html5/'+ gsh5+'.php'+ JSopts+'" scrolling="no" frameborder="0"></iframe>';fullScreenSetup();}else{if(hw>bw){hh=(bw/hw)*hh
hw=bw}
document.getElementById("Online-Stopwatch").innerHTML='<iframe src="http://www.online-stopwatch.com/html5/'+ gsh5+'.php'+ JSopts+'" width="'+ hw+'" height="'+ hh+'" scrolling="no" frameborder="0"></iframe>';}}}}
$(document).ready(function(){loadAppfile();});function ssrch(a){if("13"==a.keyCode||"b"==a)if(!(3>document.getElementById("searchbox").value.length||"Search Online-Stopwatch.com"==document.getElementById("searchbox").value))window.location="http://www.online-stopwatch.com/search/?q="+escape(document.getElementById("searchbox").value)}function schk(a){if("t"==a&&""==document.getElementById("searchbox").value)document.getElementById("searchbox").value="Search Online-Stopwatch.com",document.getElementById("searchbox").style.color="#B5B5B5";else if("Search Online-Stopwatch.com"==document.getElementById("searchbox").value)document.getElementById("searchbox").value="",document.getElementById("searchbox").style.color="#000"};var timer,offset=0,isRunning=!1,isStopwatch=!0,useDays=!1,runDispath=!1,visibleMode=!1,restartMills,dispathFunction=!1;function setVisibleMode(a){visibleMode=a}function resumePause(){isRunning?(clearInterval(timer),offset=(new Date).getTime()-offset,isRunning=!1):startTimer()}function resetTimer(){setScreen(restartMills)}
function setScreen(a){isRunning&&(clearInterval(timer),isRunning=!1);offset=restartMills;a=mills2str(a).split(":");document.title=0<a[0]?a[0]+":"+a[1]+":"+a[2]+":"+a[3]:a[1]+":"+a[2]+":"+a[3];visibleMode&&(document.getElementById("time").innerHTML=0<a[0]?a[0]+":"+a[1]+":"+a[2]+":"+a[3]:a[1]+":"+a[2]+":"+a[3],document.getElementById("mills").innerHTML=a[4]);if(!1!=runDispath)window[runDispath](a)}function startTimer(){offset=(new Date).getTime()-offset;timer=self.setInterval("run()",50);isRunning=!0}function run(){var a=(new Date).getTime(),a=isStopwatch?a-(restartMills+offset)+restartMills:restartMills+offset-a+restartMills;0<a?t=mills2str(a).split(":"):(clearInterval(timer),isRunning=!1,t=useDays?"00 00 00 00 00 000".split(" "):["00","00","00","00","000"],!1!=dispathFunction&&(new Function(dispathFunction+"("+a+")"))());document.title=0<t[0]?t[0]+":"+t[1]+":"+t[2]+":"+t[3]:t[1]+":"+t[2]+":"+t[3];visibleMode&&(document.getElementById("time").innerHTML=0<t[0]?t[0]+":"+t[1]+":"+t[2]+":"+t[3]:t[1]+":"+t[2]+":"+t[3],document.getElementById("mills").innerHTML=t[4]);!1!=runDispath&&(t.push(a),window[runDispath](t))}function str2mills(a){a=a.split(":");return useDays?864E5*a[0]+36E5*a[1]+6E4*a[2]+1E3*a[3]+1*a[4]:36E5*a[0]+6E4*a[1]+1E3*a[2]+1*a[3]}function mills2str(a){return leadZero(Math.floor(a/864E5))+":"+leadZero(Math.floor(a/36E5%24))+":"+leadZero(Math.floor(a/6E4%60))+":"+leadZero(Math.floor(a/1E3%60))+":"+leadZeros(Math.floor(a%1E3))}function leadZero(a){return 10>a?"0"+a:a}
function leadZeros(a){a=10>a?"0"+a:a;return 100>a?"0"+a:a}function jsc(a){"p"!=a&&"c"!=a?(a=a.split(":"),useDays?(restartMills=str2mills(a[0]+":"+a[1]+":"+a[2]+":"+a[3]+":"+a[4]),isStopwatch="true"==a[5]?!0:!1):(restartMills=str2mills(a[0]+":"+a[1]+":"+a[2]+":"+a[3]),isStopwatch="true"==a[4]?!0:!1),setScreen(restartMills)):resumePause()};var isFullScreen=false;function launchIntoFullscreen(){if(isFullScreen==false){$(window).scrollTop(0);$('#fframe').addClass('iframefullScreen');$('body').css('overflow','hidden');if(document.documentElement.requestFullscreen){document.documentElement.requestFullscreen();}else if(document.documentElement.mozRequestFullScreen){document.documentElement.mozRequestFullScreen();}else if(document.documentElement.webkitRequestFullscreen){document.documentElement.webkitRequestFullscreen();}else if(document.documentElement.msRequestFullscreen){document.documentElement.msRequestFullscreen();}
isFullScreen=true;}else{$('body').css('overflow','auto');$('#fframe').removeClass('iframefullScreen');if(document.exitFullscreen){document.exitFullscreen();}else if(document.mozCancelFullScreen){document.mozCancelFullScreen();}else if(document.webkitExitFullscreen){document.webkitExitFullscreen();}else if(document.msExitFullscreen){document.msExitFullscreen();}
isFullScreen=false;}}